version: "3.7"

services:
    app:
        build:
            args:
                - user=davlinux
                - uid=10000
            context: ./docker/
            dockerfile: Dockerfile
        image: dav-docker
        container_name: dav-container
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./docker/php/php-ini-overrides.ini:/usr/local/etc/php/conf.d/php-ini-overrides.ini
        networks:
            - davlaravel


    db:
        image: mysql
        container_name: dav-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: 2niteshop
            MYSQL_USER: dav-root
            MYSQL_PASSWORD: dav161
            MYSQL_ROOT_PASSWORD: dav161
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - ./docker/mysql/2niteshop.sql:/docker-entrypoint-initdb.d/2niteshop.sql
        ports:
            - "3306:3306"
        networks:
            - davlaravel


    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: always
        container_name: dav-phpmyadmin
        ports:
            - "3107:80"
        links:
            - db
        environment:
            PPMA_HOST: db
            UPLOAD_LIMIT: 10G
        networks:
            - davlaravel


    redis:
        image: redis
        restart: unless-stopped
        container_name: dav-redis
        ports:
            - "1601:80"
        networks:
            - davlaravel


    npm:
        image: node:latest
        container_name: dav-npm
        working_dir: /var/www
        restart: always
        volumes:
            - ./:/var/www
        ports:
            - "3106:80"
        networks:
            - davlaravel
        entrypoint: ["npm" , "run" , "watch"]


    nginx:
        image: nginx:alpine
        container_name: dav-nginx
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - davlaravel


networks:
    davlaravel:
        driver: bridge




